# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('curator', models.CharField(max_length=20)),
                ('tel', models.IntegerField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('create_date', models.CharField(max_length=20)),
                ('introduce', models.TextField()),
            ],
            options={
                'db_table': 't_library',
            },
        ),
    ]
