# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-17 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 't_bookcase',
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=30, null=True, verbose_name='条形码')),
                ('bookname', models.CharField(blank=True, max_length=70, null=True, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='作者')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='价格')),
                ('bookcase', models.IntegerField(blank=True, null=True, verbose_name='书架')),
                ('number', models.IntegerField(blank=True, default=1, verbose_name='馆藏数量')),
                ('borrownumber', models.IntegerField(blank=True, default=1, verbose_name='借出数量')),
                ('count', models.IntegerField(blank=True, default=0, verbose_name='借阅次数')),
            ],
            options={
                'db_table': 't_bookinfo',
            },
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('typename', models.CharField(blank=True, max_length=30, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_booktype',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('borrowtime', models.DateField(blank=True, null=True, verbose_name='借出日期')),
                ('backtime', models.DateField(blank=True, null=True, verbose_name='归还时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BookInfo')),
            ],
            options={
                'db_table': 't_borrow',
            },
        ),
        migrations.CreateModel(
            name='Giveback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('backtime', models.DateField(blank=True, null=True, verbose_name='归还时间')),
                ('operator', models.CharField(blank=True, max_length=30, null=True, verbose_name='操作者')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BookInfo')),
            ],
            options={
                'db_table': 't_giveback',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='图书馆名称')),
                ('curator', models.CharField(blank=True, max_length=10, null=True, verbose_name='馆长')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系地址')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系邮箱')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='图书馆地址')),
                ('createdate', models.DateField(blank=True, db_column='createDate', null=True, verbose_name='建管时间')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='图书馆简介')),
            ],
            options={
                'db_table': 't_library',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('pwd', models.CharField(blank=True, db_column='PWD', max_length=30, null=True)),
            ],
            options={
                'db_table': 't_manager',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='办证费')),
                ('validity', models.IntegerField(blank=True, null=True, verbose_name='有效期限')),
            ],
            options={
                'db_table': 't_parameter',
            },
        ),
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='出版社名称')),
            ],
            options={
                'db_table': 't_publishing',
            },
        ),
        migrations.CreateModel(
            name='Purview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sysset', models.IntegerField(blank=True, null=True, verbose_name='系统设置')),
                ('readerset', models.IntegerField(blank=True, null=True, verbose_name='读者管理')),
                ('bookset', models.IntegerField(blank=True, null=True, verbose_name='图书管理')),
                ('borrowback', models.IntegerField(blank=True, null=True, verbose_name='借还管理')),
                ('sysquery', models.IntegerField(blank=True, null=True, verbose_name='系统查询')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Manager')),
            ],
            options={
                'db_table': 't_purview',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='读者姓名')),
                ('barcode', models.CharField(blank=True, max_length=30, null=True, verbose_name='条形码')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('created', models.DateField(blank=True, null=True, verbose_name='创建日期')),
            ],
            options={
                'db_table': 't_reader',
            },
        ),
        migrations.CreateModel(
            name='ReaderType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='读者类型')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='可借数量')),
            ],
            options={
                'db_table': 't_readertype',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sex', models.CharField(blank=True, max_length=4, null=True, verbose_name='性别')),
            ],
            options={
                'db_table': 't_sex',
            },
        ),
        migrations.AddField(
            model_name='reader',
            name='readertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ReaderType'),
        ),
        migrations.AddField(
            model_name='reader',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Sex'),
        ),
        migrations.AddField(
            model_name='giveback',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Reader'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Reader'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='booktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BookType'),
        ),
    ]
