# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('readerName', models.CharField(max_length=30, unique=True)),
                ('rpwd', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 't_manager',
            },
        ),
    ]
