# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='pwd',
            field=models.CharField(blank=True, db_column='PWD', default=1, max_length=30),
            preserve_default=False,
        ),
    ]
