# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180917_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcase',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
